Tasks of assignment 8
Mzekala-Romanadze/TBC-_-Python-Project pull request #8
Opened 2024-03-20 06:57 UTC by Mzekala-Romanadze

2024-03-26 16:39 UTC, mishka245 requested changes
კარგია დავალება. გადახედეთ კომენტარებს

2024-03-26 16:39 UTC, mishka245 commented on Assignment_8/Task_4.py
> +    print("Decrypted text is:", output_text)
კარგია

2024-03-28 16:08 UTC, Mzekala-Romanadze commented on Assignment_8/Task_3.py
> +while c < len(user_input):
დამატებულია ახალი ფაილი.

2024-03-28 16:09 UTC, Mzekala-Romanadze commented on Assignment_8/Task_3.py
> +print(5 * first_letter, 5 * middle_letter, 5 * last_letter)
დამატებულია ახალი ფაილი.

2024-03-29 19:45 UTC, merged